services:
  - type: web
    name: todo-api
    runtime: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn todo:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TABLE_NAME
        value: Tasks
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: us-west-1
